[package]
name = "apidock"
version = "0.1.0"
description = "A pure offline API management tool"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "apidock_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
uuid = { version = "1.24.1", features = ["v4"] }
dirs = "6"
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "http2", "json", "gzip", "multipart", "query", "system-proxy", "cookies"] }
serde_urlencoded = "0.7.1"
mime_guess = "2.0.5"
tokio = { version = "1.53.1", features = ["fs"] }
regex-lite = "0.1.9"
serde_yaml_ng = "0.10.0"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

